<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-S11MJ0H" failures="1" tests="2" name="Error Validation Test" time="57.324" errors="0" timestamp="2024-02-23T02:27:14 IST">
  <testcase classname="adityaRathi.tests.ErrorValidationsTest" name="ProductErrorValidation" time="14.802">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at adityaRathi.tests.ErrorValidationsTest.ProductErrorValidation(ErrorValidationsTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- ProductErrorValidation -->
  <testcase classname="adityaRathi.tests.ErrorValidationsTest" name="submitOrder" time="0.796"/>
</testsuite> <!-- Error Validation Test -->
